# Generated by Django 3.1.2 on 2020-12-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegularTourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=3000)),
                ('distance', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('meeting_point', models.CharField(max_length=300)),
                ('route', models.CharField(max_length=300)),
                ('photo', models.CharField(max_length=50)),
                ('location_map', models.CharField(max_length=300)),
            ],
        ),
    ]
