# Generated by Django 3.1.2 on 2020-12-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regularTour', '0002_auto_20201228_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulartourmodel',
            name='destination',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='regulartourmodel',
            name='distance',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='regulartourmodel',
            name='duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='regulartourmodel',
            name='meeting_point',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='regulartourmodel',
            name='route',
            field=models.CharField(max_length=100),
        ),
    ]
