# Generated by Django 3.1.2 on 2020-12-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingmodel_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='show',
            new_name='confirmed',
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
