# Generated by Django 3.0.6 on 2020-12-20 19:58

import daftarGuide.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarGuide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=daftarGuide.models.get_image_path),
        ),
    ]
