# Generated by Django 3.0.4 on 2020-12-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarGuide', '0003_auto_20201223_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidemodel',
            name='totalTour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
