# Generated by Django 3.1.4 on 2020-12-26 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daftarGuide', '0004_guidemodel_totaltour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='guidemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
