# Generated by Django 3.1.4 on 2020-12-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarGuide', '0005_auto_20201226_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidemodel',
            name='totalTour',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
