# Generated by Django 3.1.4 on 2020-12-26 02:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regularTour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegTourScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('slot', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('language', models.CharField(max_length=50)),
                ('tourGuide', models.CharField(max_length=50)),
                ('regularTour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regularTour.regulartourmodel')),
            ],
        ),
    ]
